# Generated by Django 4.2.11 on 2024-03-31 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_active_course_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='active',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated_date',
        ),
    ]
